### PR TITLE
Add Array as a type

### PR DESCRIPTION
**Pull request by mthuret**
The idea of this PR is to allow a user to enter an array of undetermined values (while select needs determined ones).

knobs-array

I choose the string separated by comma format. Feel free to tell me if you have a better idea for the model.

### CODE REVIEW

**Comment by arunoda** [comment]
I think we could pass the separator via an the third argument. By default it could be `,`.

**Comment by mthuret** [comment]
Yes sure :)

**Comment by mthuret** [comment]
That's should be ok now

**Comment by arunoda** [comment]
Released with `v1.5.0`.

**Pull request merged**
