### PR TITLE
Fix flexbox containers in panel

### LINKED ISSUE #78: Container styles Flex Fix
I can't seem to get a local copy of `storybook-addon-knobs` to build correctly, so I'm just putting my suggestion here as an "issue." I was going to just try to PR this, but yeah, problems with building it sadly.

Would it be possible to modify some minor styling of the knobs container so that it flexes better in a panel and doesn't break panel layouts?

**Specifically...**

- Changing `width: 380,` to just `width: auto,` at https://github.com/storybooks/storybook-addon-knobs/blob/master/src/components/Panel.js#L8
- Changing `<div>` to `<div style={{width: '100%'}}>` at https://github.com/storybooks/storybook-addon-knobs/blob/master/src/components/Panel.js#L113
- Removing `maxWidth: '500px',` at https://github.com/storybooks/storybook-addon-knobs/blob/master/src/components/PropForm.js#L14

**Without the change**, here is some of the funky things happening:

 - http://bluetide.pro/RbGL/4QlTXxDv

You can see it gets caught off and doesn't scale when you adjust the panel.

**With those changes**, mentioned above, it makes the layout flex properly:

- http://bluetide.pro/wHS5/5UHnR8TV

You can see it fixes that flexing issue and works better with the layout, and doesn't cut anything off.

### PR DESCRIPTION
**Pull request by bluetidepro**
See #78 for more info. This cleans up some layout bugs inside the panel.

(Closes #78)

### CODE REVIEW

**Comment by bluetidepro** [comment]
@arunoda Do you know why the CI tests might be failing, doesn't seem like it has anything to do with my changes in this PR?

**Comment by arunoda** [comment]
@bluetidepro I have some design change requests. Could you apply them?


### Color Knob
See following image:

screen shot 2016-11-30 at 7 38 54 am

Now we click on the color knob, it shows the color popup at the end of the screen. Earlier it was not like that. Could you check on that and do something about it.

### Color and Date knob sizes

As we resize above both knobs, their size won't change. See:

screen shot 2016-11-30 at 7 39 44 am

Can we do something about it?

**Comment by bluetidepro** [comment]
@arunoda Good find, sorry, I did not see that before! I can take a look and fix those really easily.

I'm also actually currently not able to build the project because it fails on `npm install` just like the CI errors on this PR (and past recent PR's), so I didn't catch those errors.

Do you know why that may be failing? It seems like it has to do with `"typescript-definition-tester": "frederickfogerty/typescript-definition-tester#528375132cfbfd58affd401f66c02ef54813f3ce"` in `package.json`?

**Comment by arunoda** [comment]
@bluetidepro I don't find such errors.
If that's still causing issues, move that package to this: https://www.npmjs.com/package/typescript-definition-tester

I hope then it'll work.

/cc @frederickfogerty, do you have any input here?

**Comment by frederickfogerty** [comment]
The main repo now supports typescript 2.0, so the reference to my fork can be removed.

**Comment by frederickfogerty** [comment]
@bluetidepro I opened a PR on your repo https://github.com/bluetidepro/storybook-addon-knobs/pull/1

**Comment by bluetidepro** [comment]
@arunoda @frederickfogerty Okay, I fixed the bugs, and squashed the commits. I made the color picker appear in the same spot the date picker did. I made all the fields go 100% to be aligned correctly. All the fields look good, now:

screen shot 2016-11-30 at 11 00 30 am
screen shot 2016-11-30 at 11 00 34 am

**Comment by arunoda** [comment]
Yep. This is great.

**Comment by arunoda** [comment]
Released with `v1.7.1`

**Comment by bluetidepro** [comment]
Thanks @arunoda

**Pull request merged**
