### PR TITLE
Fixing performance issues

### PR DESCRIPTION
**Pull request by Gongreg**
# Fixing performance issues
## Added timestamps to setKnobs event.
If user is typing, his typing shouldn't be interrupted by randomly happening setKnobs action. Now setKnobs will actually do something only after user finishes typing.

### Example
```
const {withKnobsOptions} = require('storybook-addon-knobs');
story.addDecorator(withKnobsOptions({timestamps: true}));
```

## Added ability to pass debounce option when adding decorator
As #92 said we needed an option to add debouncing to knob changes.
I added an option to pass options when adding decorator to story.

### Example
```
const {withKnobsOptions} = require('storybook-addon-knobs');
//debounce options are wait and leading, same as in lodash.
story.addDecorator(withKnobsOptions({debounce: { wait: 100, leading: true}}));
```

## Fixing performance of field components
Fields are now extending React.PureComponent, also added deep checking if fields actually need to rerender. Didn't check performance with debug tools, but it feels smoother.

## Things to note
* Added loadash.debounce package as a dependency.
* Added lodash.isequal package as a dependency.
* Two tests changed, added timestamps so they would work.

### CODE REVIEW

**Comment by Gongreg** [comment]
Have some issues with it right now, trying to fix it.

**Comment by Gongreg** [comment]
I could also add option to add timestamps (by default it wouldn't add them). Because right now it automatically adds them.

**Comment by mthuret** [comment]
@Gongreg, thanks for this contribution :)

As it's impacted a lot of files and seems to do different things, do you mind splitting it into multiple PR, one per topics? 

Thanks a lot!

**Comment by Gongreg** [comment]
Hey,
Sure, I will try to find time this week for it. It escalated a lot during PR.

**Comment by ndelangen** [comment]
Hey @Gongreg 

Thank you so much for this PR! We're moving over to a mono-repo, since that makes a lot of sense for a project like this.
We would ❤️ it if you could create a PR here: https://github.com/storybooks/storybook

That'd be awesome, thanks!

**Pull request closed without merging**
